name            : example
description     : Example Project for snap.
version         : 2.0.0
author          : Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository      : https://github.com/aliyigitbireroglu/flutter-snap
homepage        : https://www.cosmossoftware.coffee

environment     :
  sdk: '>=2.12.0 <3.0.0'

dependencies    :
  flutter:
    sdk: flutter
  snap   :
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter         :
  uses-material-design: true
