name: snap
description: An extensive snap tool/widget for Flutter that allows very flexible snap management and snapping between your widgets.
version: 1.0.3
author: Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository: https://github.com/aliyigitbireroglu/flutter-snap
homepage: https://www.cosmossoftware.coffee

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flick: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: